### ISSUE TITLE
Make Pull Request needed to merge

### ISSUE THREAD

**Issue by Stev3eM** [myroslav111/bestellung-service#10]
Git repo so einstellen, dass nicht direkt gemerged werden kann.

**Comment by ReReRl1** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-merging-for-pull-requests (für dich myro, kann sein das es das direkt ist) @myroslav111

**Comment by myroslav111** [comment]
master is protecteted
