### ISSUE TITLE
Warenkorb anpassen

### ISSUE THREAD

**Issue by Stev3eM** [myroslav111/bestellung-service#14]
Ermöglichen Sie dem User vor Abgabe der Bestellung nochmals den Warenkorb einzusehen und gegebenenfalls zu bearbeiten.

**Comment by ReReRl1** [comment]
War doch schon davor drinnen? mit dem bearbeiten und bestätigen. Oder meinst du mit dem Ticket was anderes innerhalb der bearbeitung?
